language: node_js
node_js:
    - "10"
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
script:
    - yarn test
    - yarn run checkcov
